/*-
 * #%L
 * Mule CoAP Connector
 * %%
 * Copyright (C) 2019 - 2021 (teslanet.nl) Rogier Cobben
 * 
 * Contributors:
 *     (teslanet.nl) Rogier Cobben - initial creation
 * %%
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is
 * available at https://www.gnu.org/software/classpath/license.html.
 * 
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 * #L%
 */
package nl.teslanet.mule.connectors.coap.api.options;


import org.mule.runtime.api.meta.ExpressionSupport;
import org.mule.runtime.api.metadata.TypedValue;
import org.mule.runtime.api.util.MultiMap;
import org.mule.runtime.extension.api.annotation.Expression;
import org.mule.runtime.extension.api.annotation.param.Content;
import org.mule.runtime.extension.api.annotation.param.NullSafe;
import org.mule.runtime.extension.api.annotation.param.Optional;
import org.mule.runtime.extension.api.annotation.param.Parameter;
import org.mule.runtime.extension.api.annotation.param.display.Example;
import org.mule.runtime.extension.api.annotation.param.display.Summary;


/**
 * The option parameters of a CoAP response.
 *
 */
public class ResponseOptions
{
    /**
     * RFC 7252: The Content-Format Option indicates the representation format of
     * the message payload. The representation format is given as a numeric
     * Content-Format identifier that is defined in the "CoAP Content-Formats"
     * registry (Section 12.3).
     * 
     * @see <a href=
     *      "https://tools.ietf.org/html/rfc7252#section-5.10.3">IETF RFC 7252 -
     *      5.10.3. Content-Format</a>
     */
    @Parameter
    @Optional
    @Expression(ExpressionSupport.SUPPORTED)
    @Summary("The Content-Format Option indicates the representation format of the message payload.")
    private Integer contentFormat= null;

    /**
     * RFC 7252: The Max-Age Option indicates the maximum time a response may be
     * cached before it is considered not fresh (see Section 5.6.1).
     * 
     * The option value is an integer number of seconds between 0 and
     * {@code 2**32-1 } inclusive (about 136.1 years). A default value of 60 seconds
     * is assumed in the absence of the option in a response.
     * 
     * @see <a href=
     *      "https://tools.ietf.org/html/rfc7252#section-5.10.5">IETF RFC 7252 -
     *      5.10.5. Max-Age</a>
     */
    @Parameter
    @Optional
    @Expression(ExpressionSupport.SUPPORTED)
    @Summary("The Max-Age Option indicates the maximum time a response may be cached before it is considered not fresh.")
    private Long maxAge= null;

    /**
     * RFC 7252: An entity-tag is intended for use as a resource-local identifier
     * for differentiating between representations of the same resource that vary
     * over time. It is generated by the server providing the resource, which may
     * generate it in any number of ways including a version, checksum, hash, or
     * time. An endpoint receiving an entity-tag MUST treat it as opaque and make no
     * assumptions about its content or structure.
     * 
     * The ETag Option in a response provides the current value (i.e., after the
     * request was processed) of the entity-tag for the "tagged representation".
     * 
     * In a GET request, an endpoint that has one or more representations previously
     * obtained from the resource, and has obtained ETag response options with
     * these, can specify an instance of the ETag Option for one or more of these
     * stored responses. A server can issue a 2.03 Valid response (Section 5.9.1.3)
     * in place of a 2.05 Content response if one of the ETags given is the
     * entity-tag for the current representation, i.e., is valid; the 2.03 Valid
     * response then echoes this specific ETag in a response option.
     * 
     * @see <a href=
     *      "https://tools.ietf.org/html/rfc7252#section-5.10.6">IETF RFC 7252 -
     *      5.10.6. ETag</a>
     */
    @Parameter
    @Optional
    @Content(primary= false)
    @Expression(ExpressionSupport.SUPPORTED)
    @Summary("An entity-tag is intended for use as a resource-local identifier for differentiating between representations of the same resource.")
    private TypedValue< Object > etag= null;

    /**
     * RFC 7252: The Location-Path and Location-Query Options together indicate a
     * relative URI that consists either of an absolute path, a query string, or
     * both. A combination of these options is included in a 2.01 (Created) response
     * to indicate the location of the resource created as the result of a POST
     * request (see Section 5.8.2). The location is resolved relative to the request
     * URI.
     * 
     * Location-Path Options specify the absolute path to the resource.
     * 
     * @see <a href=
     *      "https://tools.ietf.org/html/rfc7252#section-5.10.7">IETF RFC 7252 -
     *      5.10.7. Location-Path and Location-Query</a>
     */
    @Parameter
    @Optional
    @Expression(ExpressionSupport.SUPPORTED)
    @Summary("The Location-Path specifies the absolute path to a resource that is created.")
    @Example("/some/location/on/server")
    private String locationPath= null;
    // private List< String > locationPathList= null;

    /**
     * RFC 7252: The Location-Path and Location-Query Options together indicate a
     * relative URI that consists either of an absolute path, a query string, or
     * both. A combination of these options is included in a 2.01 (Created) response
     * to indicate the location of the resource created as the result of a POST
     * request (see Section 5.8.2). The location is resolved relative to the request
     * URI.
     * 
     * Each each Location-Query Option specifies one argument parameterizing the
     * resource.
     * 
     * @see <a href=
     *      "https://tools.ietf.org/html/rfc7252#section-5.10.7">IETF RFC 7252 -
     *      5.10.7. Location-Path and Location-Query</a>
     */
    @Parameter
    @Optional
    @Expression(ExpressionSupport.SUPPORTED)
    @Summary("The Location-Query specifies the arguments parameterizing the resource that is created.")
    @Example("someparam&param1=1&param2=2")
    private String locationQuery= null;
    // private List< String > locationQueryList= null;

    /**
     * RFC 8613: The OSCORE option indicates that the CoAP message is an OSCORE
     * message and that it contains a compressed COSE object.
     * 
     * The OSCORE option includes the OSCORE flag bits.
     * 
     * @see <a href=
     *      "https://tools.ietf.org/html/rfc8613#section-2">IETF RFC 8613 - 2. The
     *      OSCORE Option</a>
     */
    //TODO add oscore feature
    //    @Parameter
    //    @Optional
    //    @Expression(ExpressionSupport.SUPPORTED)
    //    @Summary("The OSCORE option includes the OSCORE flag bits.")
    //    private String oscore= null;

    /**
     * The CoAP other options to send with the request.
     */
    @Parameter
    @Optional
    @NullSafe
    @Expression(ExpressionSupport.SUPPORTED)
    @Summary("The CoAP options to send with the request.")
    private MultiMap< String, Object > otherResponseOptions;
    // Mule does not seem to convert multimap key to Integer

    /**
     * @return the otherResponseOptions
     */
    public MultiMap< String, Object > getOtherResponseOptions()
    {
        return otherResponseOptions;
    }

    /**
     * @param otherResponseOptions the otherResponseOptions to set
     */
    public void setOtherResponseOptions( MultiMap< String, Object > otherResponseOptions )
    {
        this.otherResponseOptions= otherResponseOptions;
    }

    /**
     * @return the contentFormat
     */
    public Integer getContentFormat()
    {
        return contentFormat;
    }

    /**
     * @param contentFormat the contentFormat to set
     */
    public void setContentFormat( Integer contentFormat )
    {
        this.contentFormat= contentFormat;
    }

    /**
     * @return the maxAge
     */
    public Long getMaxAge()
    {
        return maxAge;
    }

    /**
     * @param maxAge the maxAge to set
     */
    public void setMaxAge( Long maxAge )
    {
        this.maxAge= maxAge;
    }

    /**
     * @return the etag
     */
    public TypedValue< Object > getEtag()
    {
        return etag;
    }

    /**
     * @param etag the etag to set
     */
    public void setEtag( TypedValue< Object > etag )
    {
        this.etag= etag;
    }

    /**
     * @return the locationPath
     */
    public String getLocationPath()
    {
        return locationPath;
    }

    /**
     * @param locationPath the locationPath to set
     */
    public void setLocationPath( String locationPath )
    {
        this.locationPath= locationPath;
    }

    /**
     * @return the locationQuery
     */
    public String getLocationQuery()
    {
        return locationQuery;
    }

    /**
     * @param locationQuery the locationQuery to set
     */
    public void setLocationQuery( String locationQuery )
    {
        this.locationQuery= locationQuery;
    }
}
